// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZnBrDph4XseFwWy1EsPfaH8OkVV0AVY',
    appId: '1:691755548374:web:3f7f65eacbcfb58b10d377',
    messagingSenderId: '691755548374',
    projectId: 'arkfit-app',
    authDomain: 'arkfit-app.firebaseapp.com',
    storageBucket: 'arkfit-app.firebasestorage.app',
    measurementId: 'G-L8GWGH3JK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYI5evQvLaOul6TiNz0pzkt0cX2EusnEQ',
    appId: '1:691755548374:android:26a70267b988a47510d377',
    messagingSenderId: '691755548374',
    projectId: 'arkfit-app',
    storageBucket: 'arkfit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMAkHk-8qQG9fp29XSca66q1LHpNPZWM',
    appId: '1:691755548374:ios:97bce13aa2c6443210d377',
    messagingSenderId: '691755548374',
    projectId: 'arkfit-app',
    storageBucket: 'arkfit-app.firebasestorage.app',
    androidClientId: '691755548374-apjfcf2397g4h29a5abl2t2j6dl1jv4u.apps.googleusercontent.com',
    iosClientId: '691755548374-72ovfckhjr5634ib1pj99f0kjui246ct.apps.googleusercontent.com',
    iosBundleId: 'com.kamricmedical.arkfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMAkHk-8qQG9fp29XSca66q1LHpNPZWM',
    appId: '1:691755548374:ios:e6a8ff5e775f8bf810d377',
    messagingSenderId: '691755548374',
    projectId: 'arkfit-app',
    storageBucket: 'arkfit-app.firebasestorage.app',
    androidClientId: '691755548374-apjfcf2397g4h29a5abl2t2j6dl1jv4u.apps.googleusercontent.com',
    iosClientId: '691755548374-2pkkfp1e9nl6vbnr48q38o6e2m8gqnii.apps.googleusercontent.com',
    iosBundleId: 'com.webopedian.arkfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEZnBrDph4XseFwWy1EsPfaH8OkVV0AVY',
    appId: '1:691755548374:web:769f0adbf62a24a710d377',
    messagingSenderId: '691755548374',
    projectId: 'arkfit-app',
    authDomain: 'arkfit-app.firebaseapp.com',
    storageBucket: 'arkfit-app.firebasestorage.app',
    measurementId: 'G-NXR23V71S3',
  );

}